fix date functionality and add date to more data..

diff --git a/ethos-update b/ethos-update
--- a/ethos-update
+++ b/ethos-update
@@ -37,7 +37,9 @@ if [[ $EUID -ne 0 ]]; then
 fi
 UPDATESERVER="http://get.ethosdistro.com/ethos-updates/"
 DEVELOPMENT="0"
-DATE=`date -u`
+function DATE() {
+        echo `date -u`
+}
 LOG="/var/log/ethos-update.log"
 CURLARGS="-f -s -S -k"
 SCRIPT_NEW_VERSION="$(curl $CURLARGS http://get.ethosdistro.com/ethos-updates/version/version)"
@@ -56,8 +58,8 @@ UPDATEGRUB="0"
 UPDATEINITRAMFS="0"
 UPDATEPROXY="0"
 
-echo "ethOS update on $HOSTNAME starting..."
-
+echo "$(DATE) - ethOS update on $HOSTNAME starting..."
+echo "$(DATE) - ethOS update on $HOSTNAME starting..." > /var/log/ethos-update.log
 BRANCH=`grep -Po "(?<=^branch."$HOSTNAME".)(.*)" "$CONF" | xargs`
 if [ -z "$BRANCH" ]; then
 	BRANCH=`grep -Po "(?<=^globalbranch.)(.*)" "$CONF" | xargs`
@@ -70,6 +72,11 @@ if [ $DEVELOPMENT = "0" ] ; then
   exec 1>>/var/log/ethos-update.log
   exec 2>>/var/log/ethos-update.log
 fi
+function f.function_exists() {
+    declare -f -F $1 > /dev/null
+    return $?
+}
+
 function f.updatescript() {
 		echo "Checking if ethos-update is up to date........"
 	if [ $SCRIPT_NEW_VERSION \> $SCRIPT_VERSION ]; then
@@ -106,7 +113,7 @@ function f.latest() {
 	exec 2>/dev/tty
 	cp /opt/ethos-update/updates/1.0.6/opt/ethos/sbin/ethos-motd-generator /opt/ethos/sbin/ethos-motd-generator
 	cp /opt/ethos-update/updates/1.0.6/opt/ethos/sbin/ethos-readconf /opt/ethos/sbin/ethos-readconf
-	echo "Your version of ethOS is up to date. Version: $ETHOSVERSION"	
+	echo "$(DATE) Your version of ethOS is up to date. Version: $ETHOSVERSION"	
 }
 
 	
@@ -115,25 +122,27 @@ function f.latest-develop() {
 	exec 2>/dev/tty
 	cp /opt/ethos-update/updates/1.0.6/opt/ethos/sbin/ethos-motd-generator /opt/ethos/sbin/ethos-motd-generator
 	cp /opt/ethos-update/updates/1.0.6/opt/ethos/sbin/ethos-readconf /opt/ethos/sbin/ethos-readconf
-	echo "Your version of ethOS is up to date. Version: $ETHOSVERSION"	
+	echo "$(DATE) Your version of ethOS is up to date. Version: $ETHOSVERSION"	
 }
 
 function f.prerun() {
-	echo "Running Pre-Update Commands"
+	echo "$(DATE) Running Pre-Update Commands"
 	echo "$ETHOSVERSION" > /opt/ethos/etc/oldversion
 	exec 1>/dev/tty
 	exec 2>/dev/tty
-	echo "$DATE Updating ethos to version $NEWVERSION, May take up to $TIMEREQUIRED minutes depending on your connection speed. You can log in on another session and type tail -f /var/log/ethos-update.log to view progress"
+	echo "$(DATE) Updating ethos to version $NEWVERSION, May take up to $TIMEREQUIRED minutes depending on your connection speed. You can log in on another session and type tail -f /var/log/ethos-update.log to view progress"
 	if [ $DEVELOPMENT = "0" ] ; then
 	  exec 1>>/var/log/ethos-update.log
 	  exec 2>>/var/log/ethos-update.log
 	fi
 	ALLOWED=`cat /opt/ethos/etc/allow.file`
-	echo "Disallowing and stopping mining during the update process..."
+	echo "$(DATE) Disallowing and stopping mining during the update process..."
 	/opt/ethos/bin/disallow
 	/opt/ethos/bin/minestop
 	/usr/bin/dpkg --configure -a
-
+	if function_exists "f.$NEWVERSION-extra-files"; then
+		f.$NEWVERSION-extra-files
+	fi
 }
 function f.copycorefiles() {
         shopt -s globstar;shopt -s dotglob;cd "$BASE";FILES=( `echo **` )
@@ -159,7 +168,6 @@ function f.copycorefiles() {
         dkms install alx/2.0
         rm -rf /tmp/alx
 	fi
-
 }
 function f.setpermissions() {
         chown -R ethos.ethos /home/ethos
@@ -177,7 +185,7 @@ function f.1.0-extra-installs() {
 	mv /home/ethos/local /home/ethos/local.conf
 	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 437D05B5 3E5C1192
 #Install new ati drivers
-  	/usr/bin/apt-get update
+  	/usr/bin/apt-get -qq update
   	/usr/bin/apt-get -fy install dos2unix nitrogen tmux mc nload xfce4-terminal
   	/usr/bin/apt-get --only-upgrade -yo Dpkg::Options::="--force-confnew" install \
  	base-files bind9-host ca-certificates cpio cpp-4.8 dnsutils eog \
@@ -198,25 +206,25 @@ function f.1.0-extra-installs() {
   	pm-utils python-ibus ssh-askpass-gnome systemd-services sysv-rc \
   	sysvinit-utils thermald udev usbutils 
 }
-function f.1.0.6-extrafiles() {
+function f.1.0.6-extra-files() {
 	if [ ! -f "/usr/bin/hexchat" ]; then
-		/usr/bin/apt-get update
+		/usr/bin/apt-get -qqupdate
 		/usr/bin/apt-get -fy install hexchat
 		rm -f /usr/share/xfce4/helpers/firefox.desktop
 	fi
 }
-function f.1.0.7-extrafiles() {
+function f.1.0.7-extra-files() {
 	sed -i '/^deb http\:\/\/llvm.org\/apt\/trusty\/ llvm-toolchain-trusty-3.7 main/d' /etc/apt/sources.list
 	sed -i '/^# deb-src http\:\/\/llvm.org\/apt\/trusty\/ llvm-toolchain-trusty-3.7 main/d' /etc/apt/sources.list
 	
 	if [ ! -f "/usr/bin/irssi" ]; then
-		/usr/bin/apt-get update
+		/usr/bin/apt-get -qq update
 		/usr/bin/apt-get -fy install irssi
 		rm -f /usr/share/xfce4/helpers/firefox.desktop
 	fi
 }
 function f.postrun() {
-	echo "Running Post-Update Commands"
+	echo "$(DATE) Running Post-Update Commands"
 	f.setpermissions
 	echo "$NEWVERSION_NUMBER" > /opt/ethos/etc/version
 	/bin/rm -f /home/ethos/.ethash/full*
@@ -270,16 +278,16 @@ function f.postrun() {
 	rm -rf /var/cache/apt/*
 	if [ "$ALLOWED" -eq "0" ]; then
 		echo "0" > /opt/ethos/etc/allow.file
-		echo "$DATE - Mining Disallowed before script start, keeping it that way."
+		echo "$(DATE) - Mining Disallowed before script start, keeping it that way."
 	else
 		echo "1" > /opt/ethos/etc/allow.file
-		echo "$DATE - Mining Allowed before script start, keeping it that way."
+		echo "$(DATE) - Mining Allowed before script start, keeping it that way."
 	fi
 	exec 1>/dev/tty
 	exec 2>/dev/tty
 	sync
 	sleep 10
-	echo "$DATE - ethOS Update on $HOSTNAME Finished, please reboot. see /var/log/ethos-update.log for details about what was updated."
+	echo "$(DATE) - ethOS Update on $HOSTNAME Finished, please reboot. see /var/log/ethos-update.log for details about what was updated."
 	exit 0
 }
 function f.1.0-1.0.6(){
@@ -292,7 +300,6 @@ function f.1.0-1.0.6(){
 		UPDATEINITRAMFS="1"
 		f.prerun
 		f.1.0-extra-installs
-		f.1.0.6-extrafiles
 		f.copycorefiles
 		f.postrun
 }
@@ -305,7 +312,6 @@ function f.1.0.3-1.0.6(){
 		UPDATEATITWEAK="0"
 		UPDATEINITRAMFS="1"
 		f.prerun
-		f.1.0.6-extrafiles
 		f.copycorefiles
 		f.postrun
 }
@@ -316,7 +322,6 @@ function f.1.0.4-1.0.6(){
 		NEWVERSION="1.0.6"
 		TIMEREQUIRED="3"
 		f.prerun
-		f.1.0.6-extrafiles
 		f.copycorefiles
 		f.postrun
 }
@@ -348,6 +353,7 @@ function f.1.0.3-develop(){
 }
 function f.1.0.4-develop(){
 		UPDATEPROXY="1"
+		UPDATEGRUB="1"
 		BASE="/opt/ethos-update/updates/$DEVELOPVERSION"
 		NEWVERSION="$DEVELOPVERSION"
 		TIMEREQUIRED="3"
