add logic if download fails
add logic for if download fails

diff --git a/ethos-update b/ethos-update
--- a/ethos-update
+++ b/ethos-update
@@ -52,8 +52,13 @@ function f.updatescript() {
 	if [ $SCRIPT_NEW_VERSION \> $SCRIPT_VERSION ]; then
 		echo "Getting latest version of ethos-update"
 		wget https://github.com/sling00/ethos-update/tarball/master -O /tmp/ethos-update.tar.gz
-		 tar xz /tmp/ethos-update.tar.gz -C /tmp/ethos-update/
-#		download /tmp/ethos-update.tar $UPDATESERVER/ethos-update/ethos-update.tar
+		if [ $? = "0" ]; then 
+		tar xz /tmp/ethos-update.tar.gz -C /tmp/ethos-update/
+		else 
+			echo "Failed to download update from repo, try again in a few minutes."
+			exit 0
+		fi
+		#download /tmp/ethos-update.tar $UPDATESERVER/ethos-update/ethos-update.tar
 #		tar xvf /tmp/ethos-update.tar -C /opt/ethos > /var/log/ethos-update.log
 		echo "Updated to latest version, relaunching."
 #		rm /tmp/ethos-update.tar
