add sgminer-gm

diff --git a/ethos-update b/ethos-update
--- a/ethos-update
+++ b/ethos-update
@@ -602,7 +602,11 @@ function f.install-amdgpu-1.1.2(){
   if [ $? != "0" ];then
     echo "md5sum of ethos-1.1.2-files.tar.xz does not match!"
   fi
-    tar xf /tmp/ethos-1.1.2-files/fglrx-patches-4.8-ethos1.tar.xz -C /
+  
+  mkdir -p /opt/miners/
+  tar xf /tmp/ethos-1.1.2-files/sgminer-gm-ethos1.tar.xz -C /opt/miners/ || echo "extract of sgminer-gm-ethos1.tar.xz failed"
+  
+  tar xf /tmp/ethos-1.1.2-files/fglrx-patches-4.8-ethos1.tar.xz -C /
   if [ $? != "0" ];then
    echo "extract of fglrx-patches-4.8-ethos1.tar.xz failed!"
   fi
