Update ethos-update

diff --git a/ethos-update b/ethos-update
--- a/ethos-update
+++ b/ethos-update
@@ -422,11 +422,12 @@ function f.1.1.2-extra-files(){
   #Cleanup the old amdgpu files...
   rm -f /opt/driver-switching/amdgpu/etc/amd/amdapfxx.blb
   rm -f /opt/driver-switching/amdgpu/vulkan/icd.d/amd_icd64.json
+  
   PACKAGES_ADD="socat "
   PACKAGES_MARK="hwdata thermald acl bc diffstat gettext tlsutils udisks2 update-inetd patchutils dconf-cli libfs6 x11-apps x11-session-utils x11-xfs-utils xinit" 
   #PACKAGES_REMOVE="$PACKAGES_REMOVE libegl1-amdgpu-pro libegl1-amdgpu-pro-dev libgbm-amdgpu-pro-dev libgbm1-amdgpu-pro libgl1-amdgpu-pro-dev libgl1-amdgpu-pro-glx\
   # libgl1-amdgpu-pro-dri libgles2-amdgpu-pro libgles2-amdgpu-pro-dev amdgpu-pro-vulkan-driver libvdpau-amdgpu-pro xserver-xorg-video-amdgpu-pro amdgpu-pro-dkms\
-  PACKAGES_REMOVE="$PACKAGES_REMOVE sudo apt remove amdgpu-pro amdgpu-pro-core amdgpu-pro-clinfo amdgpu-pro-computing amdgpu-pro-dkms\
+  PACKAGES_REMOVE="$PACKAGES_REMOVE amdgpu-pro amdgpu-pro-core amdgpu-pro-clinfo amdgpu-pro-computing amdgpu-pro-dkms\
   amdgpu-pro-firmware amdgpu-pro-graphics amdgpu-pro-libopencl-dev amdgpu-pro-libopencl1 amdgpu-pro-opencl-icd\
   amdgpu-pro-vulkan-driver libdrm-amdgpu-pro-amdgpu1 libdrm-amdgpu-pro-tools libdrm-amdgpu-pro-dev libdrm-amdgpu1\
   libdrm2-amdgpu-pro libegl1-amdgpu-pro libegl1-amdgpu-pro-dev libgbm-amdgpu-pro-dev libgbm1-amdgpu-pro libgl1-amdgpu-pro-dev\
@@ -510,7 +511,28 @@ function f.1.1.2-extra-files(){
 }
 function f.install-amdgpu-1.1.2(){
   mkdir -p /tmp/ethos-1.1.2-files/
-  curl -o /tmp/ethos-1.1.2-files.tar.xz http://162.243.39.238/packages/1.1.0/ethos-1.1.0-files.tar.xz
+  curl -o /tmp/ethos-1.1.2-files.tar.xz http://$MIRRORIP/packages/1.1.0/ethos-1.1.0-files.tar.xz
+  #Install new kernel
+  if [ $? != "0" ];then
+    echo "Download of ethos-1.1.2-files.tar.xz failed"
+  fi
+  tar xf /tmp/ethos-1.1.2-files.tar.xz -C /tmp/ethos-1.1.2-files/
+  if [ $? != "0" ];then
+    echo "extract of ethos-1.1.2-files.tar.xz failed"
+  fi
+  cd /tmp/ethos-1.1.2-files; md5sum -c /tmp/ethos-1.1.2-files/md5sum.txt
+  if [ $? != "0" ];then
+    echo "md5sum of ethos-1.1.2-files.tar.xz does not match!"
+  fi
+    tar xf /tmp/ethos-1.1.2-files/fglrx-patches-4.8-ethos1.tar.xz -C /
+  if [ $? != "0" ];then
+   echo "extract of fglrx-patches-4.8-ethos1.tar.xz failed!"
+  fi
+  f.checkdpkg
+  echo "Installing new kernel / amdgpu packages..."
+  sudo dpkg -i linux-libc-dev_4.8.0-rc6-ethos3-1_amd64.deb linux-headers-4.8.0-rc6-ethos3_4.8.0-rc6-ethos3-1_amd64.deb\
+  linux-firmware-image-4.8.0-rc6-ethos3_4.8.0-rc6-ethos3-1_amd64.deb\
+  linux-image-4.8.0-rc6-ethos3_4.8.0-rc6-ethos3-1_amd64.deb
 sudo dpkg -i amdgpu-pro-firmware_16.30.3-315407-ethos2_amd64.deb
 sudo dpkg -i amdgpu-pro_16.30.3-315407-ethos2_amd64.deb amdgpu-pro-clinfo_16.30.3-315407-ethos2_amd64.deb amdgpu-pro-computing_16.30.3-315407-ethos2_amd64.deb amdgpu-pro-opencl-icd_16.30.3-315407-ethos2_amd64.deb amdgpu-pro-libopencl1_16.30.3-315407-ethos2_amd64.deb libdrm2-amdgpu-pro_16.30.3-315407-ethos2_amd64.deb
 
