push file from upstream

diff --git a/updates/1.1.1/opt/ethos/sbin/check-opencl b/updates/1.1.1/opt/ethos/sbin/check-opencl
--- a/updates/1.1.1/opt/ethos/sbin/check-opencl
+++ b/updates/1.1.1/opt/ethos/sbin/check-opencl
@@ -22,48 +22,36 @@ if [ "$DRIVER" = "fglrx" ] || [ "$DRIVER" = "amdgpu" ];then
   echo -n "" > /var/run/ethos/wrong_driver.file
   chown ethos.ethos /var/run/ethos/wrong_driver.file
 
-  
   if [ "$DRIVER" = "amdgpu" ] && [ "$NEEDAMDGPU" = "0" ];then
-    ERR="WARNING: DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
-    ERR="$ERR ! WRONG DRIVER, ADD \"driver [worker] fglrx\" TO CONFIG (worker is 6-digit rig name)"
+    ERR="WRONG DRIVER! ADD \"driver [worker] fglrx\" TO CONFIG ([worker] is 6-digit rig name)"
     echo "1" > /var/run/ethos/wrong_driver.file
     sleep 3
   elif [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" = "1" ];then
-    ERR="WARNING: DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
-    ERR="$ERR ! WRONG DRIVER, ADD \"driver [worker] amdgpu\" TO CONFIG (worker is 6-digit rig name)"
+    ERR="WRONG DRIVER! ADD \"driver [worker] amdgpu\" TO CONFIG ([worker] is 6-digit rig name)"
     echo "1" > /var/run/ethos/wrong_driver.file
   fi
   timeout $TIMEOUT /usr/bin/clinfo > /dev/null
 
-
-  
-  if [ "$DRIVER" = "amdgpu" ] && [ $? -ne "0" ] && [ "$NEEDAMDGPU" = "1" ];then
-    ERR="WARNING: DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
+  if [ $? -ne "0" ];then
+    ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
     echo "1" > /var/run/adl_error.file
-
-  elif [ "$DRIVER" = "fglrx" ] && [ $? -ne "0" ] && [ "$NEEDAMDGPU" = "0" ]; then
-  	ERR="WARNING: DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE\n"
-  	echo "1" > /var/run/adl_error.file
   fi
-
 
   if [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" = "0" ];then
     timeout $TIMEOUT /usr/local/bin/atitweak -s 
     if [ $? -ne "0" ]; then
-      echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
-    	echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/ethos-log.file
-      echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/miner.output
+      ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE" 
       echo "1" > /var/run/adl_error.file
-	    sleep 3
-      echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
     fi
   fi
 fi
+
 if [ ! -z "$ERR" ];then
 	echo "$ERR" | wall 
 	echo "$ERR" >> /var/run/ethos-log.file
 	echo "$ERR" >> /var/run/miner.output
 
 fi
+
 /opt/ethos/bin/amdmeminfo -o -s -q > /var/run/meminfo.file
 
